### ISSUE TITLE
AppBar button displays off edge of page between 960px and 1100px wide

### ISSUE THREAD

**Issue by techfoundrynz** [alexplumb/material-ui-banner#1]
Buttons within the banner flow off the edge of the page when the screen size ie between 960px and 1100px wide as the width of the banner is set to 1100px. 

Adding a maximum width of 100% to the container should resolve the issue.

appBar: {
    [theme.breakpoints.up('md')]: {
      width: 1100,
      marginLeft: 'auto',
      marginRight: 'auto',
      maxWidth: '100%',
    },
  },

<img width="1097" alt="screen shot 2019-02-21 at 3 49 53 pm" src="https://user-images.githubusercontent.com/13304863/53140063-6d149780-35f0-11e9-8170-e23180c2628d.png">

**Comment by alexplumb** [comment]
Thanks for the feedback @contactsimonwilson! This should be fixed now.

**Comment by techfoundrynz** [comment]
Thanks for getting to these @alexplumb
