### ISSUE TITLE
TypeError: Cannot read property 'up' of undefined

### ISSUE THREAD

**Issue by charlax** [alexplumb/material-ui-banner#5]
I'm getting the following exception with a plain install:

```
(anonymous function)
node_modules/material-ui-banner/dist/index.js:192
  189 |   marginLeft: "auto",
  190 |   marginRight: "auto"
  191 | },
> 192 | appBar: O({}, e.breakpoints.up("md"), {
      | ^  193 |   width: 1100,
  194 |   marginLeft: "auto",
  195 |   marginRight: "auto",
View compiled
create
node_modules/@material-ui/styles/esm/getStylesCreator/getStylesCreator.js:20
  17 | var styles;
  18 | 
  19 | try {
> 20 |   styles = themingEnabled ? stylesOrCreator(theme) : stylesOrCreator;
```

Looks like it's not finding the theme? I'll continue to investigate.

**Comment by charlax** [comment]
I guess the issue comes from the fact that I have installed my theme in the `@material-ui/core`'s `ThemeProvider`, but not in `@material-ui/styles`'s `ThemeProvider`.

https://material-ui.com/customization/default-theme/#material-ui-core-styles-vs-material-ui-styles

**Comment by charlax** [comment]
A bit related to https://github.com/mui-org/material-ui/issues/15867

I'm wondering if you should rather `import withStyles from '@material-ui/core/withStyles'`...

**Comment by alexplumb** [comment]
@charlax Sorry for the delay in getting back to you. v4 of material-ui says to use `import withStyles from '@material-ui/styles/withStyles'`, so that's what this app will continue to use.

**Comment by charlax** [comment]
It would be nice for `material-ui` to provide guidelines for libraries using it. Where are you reading this? `material-ui-pickers`, which is blessed by `material-ui`'s creator does import from `@material-ui/core/styles` - **not** from `@material-ui/styles`.

See this search: (ignoring the docs and examples results, which seem outdated)

https://github.com/mui-org/material-ui-pickers/search?q=material-ui%2Fstyles&unscoped_q=material-ui%2Fstyles

**Comment by charlax** [comment]
I opened an issue on `@material-ui/core` to get a clarification. In the meantime, this new documentation page implies that you should use `@material-ui/core/styles`:

https://material-ui.com/getting-started/faq/#i-have-several-instances-of-styles-on-the-page

**Comment by charlax** [comment]
Just to close the loop here: `material-ui`'s author confirmed that you should use `@material-ui/core/styles`.

**Comment by alexplumb** [comment]
@charlax Thanks for taking the charge on getting that answered. I'll deploy an update shortly.

**Edit** - Deployed in `1.3.1`

**Comment by charlax** [comment]
Thanks @alexplumb !
